apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: manager
subjects:
- kind: ServiceAccount
  name: cnpg-manager
  namespace: cnpg-system
